name: Upload to DAFNI

on:
  release:
    types: [published]

jobs:
  release:
    name: Upload to DAFNI
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Docker Build
        run: docker build -t hbv-setup .

      - name: Compress docker image
        run: docker save hbv-setup | gzip > hbv-setup.tar.gz

      - name: Set tag as env
        run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Upload to DAFNI
        uses: dafnifacility/dafni-model-uploader@v1.9
        with:
          definition-path: './model-definition.yml'
          image-path: './hbv-setup.tar.gz'
          username: ${{ secrets.DAFNI_SERVICE_ACCOUNT_USERNAME }}
          password: ${{ secrets.DAFNI_SERVICE_ACCOUNT_PASSWORD }}
          version-message: ${{ env.TAG }}
          parent-model: '99de1765-d905-4984-b62e-414b39fcefe9'
